Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: io.github.realyusufismail.QuranSkillHandler
      CodeUri: /Users/YI/Documents/GitHub/QuranSkill/target/QuranSkill-1.0-SNAPSHOT.jar
      Runtime: java11
      Architectures:
        - x86_64